version: 2
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1611523371
layout:
  /header/: {  }
  /navigation/:
    -
      - 'logo-4689 22'
      - 'menu-4196 78'
  /showcase/:
    -
      - position-position-4974
  /feature/:
    -
      - custom-4216
    -
      - 'position-position-2382 33.3'
      - 'position-position-1330 33.3'
      - 'position-position-2771 33.3'
  /main/:
    -
      - position-position-5312
    -
      - position-position-6039
  /subfeature/:
    -
      - sample-7514
    -
      - owl-testimonios-2964
    -
      - 'sample-3380 65'
      - 'social-pro-6726 35'
  /footer/:
    -
      - position-footer
    -
      - 'position-position-9294 33.3'
      - 'position-position-7469 33.3'
      - 'position-position-2072 33.3'
    -
      - copyright-7412
  offcanvas:
    -
      - mobile-menu-1683
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  showcase:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  subfeature:
    type: section
    attributes:
      class: flush
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  logo-4689:
    title: 'Logo / Image'
    block:
      variations: 'align-left nopaddingall'
  menu-4196:
    attributes:
      menu: mainmenu
    block:
      variations: align-right
  position-position-4974:
    title: Animacion
    attributes:
      key: animacion
      chrome: none
    block:
      variations: full-width
  custom-4216:
    title: texto
    attributes:
      html: "<h1>Las mejores Marcas de ropa Infatil</h1>\n<p>Disfrutamos vistiendo a las princesas de la casa.</p>\n"
    block:
      variations: center
  position-position-2382:
    title: calzado
    attributes:
      key: vendidos-1
      chrome: none
    block:
      fixed: '1'
  position-position-1330:
    title: Accesorios
    attributes:
      key: vendidos-2acce
      chrome: none
    block:
      fixed: '1'
  position-position-2771:
    title: Ropa
    attributes:
      key: vendidos-3zap
      chrome: none
    block:
      fixed: '1'
  position-position-5312:
    title: informacion
    attributes:
      key: inicio-contenido
      chrome: none
  position-position-6039:
    title: 'Formulario de registro'
    attributes:
      key: formulario-registro
      chrome: none
  sample-7514:
    title: servicios
    attributes:
      image: ''
      headline: ''
      description: ''
      link: ''
      linktext: ''
      samples:
        -
          icon: 'fa fa-check-circle-o'
          subtitle: ''
          description: ''
          id: ''
          class: ''
          variations: ''
          title: 'Pagos 100% Garantizados'
        -
          icon: 'fa fa-clock-o'
          subtitle: ''
          description: ''
          id: ''
          class: ''
          variations: ''
          title: '30 dias para cambiar de opinion'
        -
          icon: 'fa fa-commenting-o'
          subtitle: ''
          description: ''
          id: ''
          class: ''
          variations: ''
          title: 'Atencion al cliente Correo y Telefono'
        -
          icon: 'fa fa-star-o'
          subtitle: ''
          description: ''
          id: ''
          class: ''
          variations: ''
          title: 'Maxima garantia de calidad'
  owl-testimonios-2964:
    title: 'Owl Testimonios'
    attributes:
      tituloprincipal: ''
      etiquetatitulo: h2
      disenotestimonio: diseno-testi9
      items:
        -
          nombre: ''
          imagenautor: 'gantry-media://Logopinkf.png'
          puestotrabajo: 'Compra por Whatsapp'
          contenidotesti: 'Recoge y paga tu pedido en Tienda'
          name: anuncio1
        -
          nombre: ''
          imagenautor: 'gantry-media://Logopinkf.png'
          puestotrabajo: 'Compra por correo'
          contenidotesti: 'Envio gratis a partir de $849MXN'
          name: anuncio2
        -
          nombre: ''
          imagenautor: 'gantry-media://Logopinkf.png'
          puestotrabajo: 'Entrega en tienda Gratis'
          contenidotesti: 'El costo de envi√≥ es gratis'
          name: anuncio3
      breakpoint1minimo: '0'
      breakpoint1numslides: '1'
      breakpoint1dots: '1'
      breakpoint1nav: '1'
      breakpoint2minimo: '480'
      breakpoint2numslides: '2'
      breakpoint2dots: '1'
      breakpoint2nav: '1'
      breakpoint3minimo: '768'
      breakpoint3numslides: '3'
      breakpoint3dots: '1'
      breakpoint3nav: '1'
      anchualtuimagen: 5rem
      tamanotextonombre: 1.1rem
      colortextonombre: '#2b282b'
      tamanotextocargo: ''
      colortextocargo: ''
      tamanotextotestimonio: ''
      colortextotestimonio: ''
      maxcaracteres: ''
      loop: '1'
      autoplay: '1'
      autoplaySpeed: '1'
      pauseOnHover: '1'
      prevText: Anterior
      nextText: Siguiente
      posicionbotonesnav: posicionbotonesnav_abajo
      colorbotonesnav: ''
      slideby: '1'
      class: ''
      animateIn: fadeIn
      animateOut: fadeOut
  sample-3380:
    title: 'tarjetas de pago'
    attributes:
      image: 'gantry-media://tarjetapagos.png'
      headline: ''
      description: ''
      link: ''
      linktext: ''
      samples: {  }
  social-pro-6726:
    title: 'Redes Sociales'
    attributes:
      css:
        class: social
      tituloprincipal: 'Siguenos en:'
      etiquetatitulo: h2
      orientacionitems: g-social-dis-horizontal
      target: _blank
      display: ambos
      colortexto: ''
      textodebajo: '0'
      diseno: diseno5
      items:
        -
          icon: 'fa fa-facebook fa-3x'
          text: ''
          link: 'http://www.facebook.com'
          coloricono: '#0489c2'
          name: Facebook
        -
          icon: 'fa fa-whatsapp fa-3x'
          text: ''
          link: 'http://www.whatsapp.com'
          coloricono: '#87e8bb'
          name: Whatsapp
        -
          icon: 'fa fa-instagram fa-3x'
          text: ''
          link: 'http://www.instagram.com'
          coloricono: '#d697ed'
          name: Instagram
        -
          icon: 'fa fa-envelope-o fa-3x'
          text: ''
          link: 'http://www.hotmail.com'
          coloricono: '#f05775'
          name: Email
  position-footer:
    attributes:
      key: footer
  position-position-9294:
    title: 'Sobre Nosotros'
    attributes:
      key: pie-pag1
  position-position-7469:
    title: Horarios
    attributes:
      key: pie-pag2
      chrome: none
  position-position-2072:
    title: Contacto
    attributes:
      key: pie-pag3
      chrome: none
  copyright-7412:
    attributes:
      date:
        start: '2014'
      owner: 'Pink Fashion Boutique. Todos los derechos reservados'
    block:
      variations: center
  mobile-menu-1683:
    title: 'Mobile Menu'
